      *---------------------------------------------------------------*
      *    Standard fuer alle Objekte unter PVCS VM
      *            Datum      :  15.04.2013
      *            Kategorie  :  Copystrecke
      *---------------------------------------------------------------*
      *
      *---------------------------------------------------------------*
      *    Copyright (c) 2013 ATLAS Dienstleistungen f. V. GmbH
      *---------------------------------------------------------------*
      *    $Workfile:   DRKI2748.CPY  $
      *    $Revision:   2.1  $
      *
      *    $Log:   L:/mf/CPY/DRKI2748.CPv  $
      *
      *   Rev 2.1   Jun 12 2013 10:51:32   t13ex27
      *AKI01204: SEPA - DB-Online-Adressen-Programme
      *
      *   Rev 2.0   Apr 15 2013 11:06:26   t13ex27
      *Archiverstellung
      *
      *---------------------------------------------------------------*
       01  PI-ZXKI0455.
           05 PI-ZXKI0455-FUNKTION            PIC X(008).
              88 PI-ZXKI0455-DRKI2749-LIST        VALUE 'DRKI2749'.

