      ****************************************************************          
      *    COPY-MEMBER: DRKI3697                                     *          
      *    ----------------------------------------------------------*          
      *    SCHNITTSTELLE FÜR DAS UPRO ZTKI0499                       *          
      *    MIT DEN DATEN, DIE EINMAL PRO UPRO ÜBERGEBEN WERDEN       *          
      *    ----------------------------------------------------------*          
      ****************************************************************          
      *   ERZEUGT MIT OZPGEN         06.02.2023 / 13:47:24 / U131774            
      ****************************************************************          
      *    VERSION                                                              
      ****************************************************************          
      * AENDERUNGEN:                                                 *          
      * AUFTRAG ! DATUM  !VER ! AENDERUNG                 ! NAME     *          
      * -------------------------------------------------------------*          
      *         !        !    !                           !          *          
      *         !        !    !                           !          *          
      *                                                              *          
      * ENDE-LOGBUCH                                                 *          
      ****************************************************************          
      *                                                                         
      *    DIESES COPY ENTHÄLT DIE INFORMATIONEN, DIE EINMAL                    
      *    PRO UPRO ÜBERGEBEN WERDEN.                                           
      *    ALSO NICHT: DATEN, DIE PRO FUNKTION ÜBERGEBEN WERDEN                 
      *                (IN SEPARATEN COPYS PRO FUNKTION)                        
      *                                                                         
      ****************************************************************          
      *                                                                         
       01  PI-ZTKI0499.                                                         
           05  PI-ZTKI0499-FUNKTION              PIC  X(008).                   
                                                                                
                                                                                
             88   PI-ZTKI0499-DRKI3698     VALUE 'DRKI3698'.                    
             88   PI-ZTKI0499-DRKI3699     VALUE 'DRKI3699'.                    
             88   PI-ZTKI0499-DRKI3700     VALUE 'DRKI3700'.                    
             88   PI-ZTKI0499-DRKI3701     VALUE 'DRKI3701'.                    
                                                                                
      *                                                                         
      ******* ENDE COPY-MEMBER **************************************           
