      *---------------------------------------------------------------*
      *    Standard fuer alle Objekte unter PVCS VM
      *            Datum      :  05.09.2012
      *            Kategorie  :  Copystrecke
      *---------------------------------------------------------------*
      *
      *---------------------------------------------------------------*
      *    Copyright (c) 2012 ATLAS Dienstleistungen f. V. GmbH
      *---------------------------------------------------------------*
      *    $Workfile:   DRKI2672.CPY  $
      *    $Revision:   2.2  $
      *
      *    $Log:   L:/mf/CPY/DRKI2672.CPv  $
      *
      *   Rev 2.2   Sep 06 2012 19:49:34   t13ex39
      *AKI01175: DeuBa-Anspracheschutz: Anpassungen in DeuBa-Aktual
      *isierung
      *
      *   Rev 2.1   Sep 06 2012 19:41:24   t13ex39
      *AKI01175: DeuBa-Anspracheschutz: Anpassungen in DeuBa-Aktual
      *isierung
      *
      *   Rev 2.0   Sep 5 2012 07:38:15 T13EX39
      *Archiverstellung
      *
      *---------------------------------------------------------------*
      ****************************************************************
      *    COPY-MEMBER: DRKI2672                                     *
      *    ----------------------------------------------------------*
      *    SCHNITTSTELLE FÜR DAS UPRO ZTKI0454                       *
      *    MIT DEN DATEN, DIE EINMAL PRO UPRO ÜBERGEBEN WERDEN       *
      *    ----------------------------------------------------------*
      ****************************************************************
      *   ERZEUGT MIT OZPGEN         05.09.2012 / 07:38:15 / T13EX39
      ****************************************************************
      *    VERSION
      ****************************************************************
      * AENDERUNGEN:                                                 *
      * AUFTRAG ! DATUM  !VER ! AENDERUNG                 ! NAME     *
      * -------------------------------------------------------------*
      *         !        !    !                           !          *
      *         !        !    !                           !          *
      *                                                              *
      * ENDE-LOGBUCH                                                 *
      ****************************************************************
      *
      *    DIESES COPY ENTHÄLT DIE INFORMATIONEN, DIE EINMAL
      *    PRO UPRO ÜBERGEBEN WERDEN.
      *    ALSO NICHT: DATEN, DIE PRO FUNKTION ÜBERGEBEN WERDEN
      *                (IN SEPARATEN COPYS PRO FUNKTION)
      *
      ****************************************************************
      *
       01  PI-ZTKI0454.
           05  PI-ZTKI0454-FUNKTION              PIC  X(008).


             88   PI-ZTKI0454-DRKI2673     VALUE 'DRKI2673'.
             88   PI-ZTKI0454-DRKI2674     VALUE 'DRKI2674'.

      *
      ******* ENDE COPY-MEMBER **************************************
