      *---------------------------------------------------------------* 
      *    Standard fuer alle Objekte unter PVCS VM                     
      *            Datum      :  21.09.2010                             
      *            Kategorie  :  Copystrecke                            
      *---------------------------------------------------------------* 
      *                                                                 
      *---------------------------------------------------------------* 
      *    Copyright (c) 2010 ATLAS Dienstleistungen f. V. GmbH         
      *---------------------------------------------------------------* 
      *    $Workfile:   DRKI2421.CPY  $                                      

      *    $Revision:   2.1  $                                          
      *                                                                 
      *    $Log:   L:/mf/CPY/DRKI2421.CPv  $                             
      *
      *   Rev 2.1   Sep 29 2010 10:50:24   t13ex14
      *AKI00966: DVAG Österreich: DB-Objekte
      *                                                                 
      *   Rev 2.0   Sep 21 2010 14:43:08 T13EX14                        
      *Archiverstellung                                                 
      *                                                                 
      *---------------------------------------------------------------* 
      ****************************************************************  
      *    COPY-MEMBER: DRKI2421                                     *  
      *    ----------------------------------------------------------*  
      *    SCHNITTSTELLE FšR DAS UPRO ZTKI0445                       *  
      *    MIT DEN DATEN, DIE EINMAL PRO UPRO šBERGEBEN WERDEN       *  
      *    ----------------------------------------------------------*  
      ****************************************************************  
      *   ERZEUGT MIT OZPGEN         23.09.2010 / 15:20:31 / T13EX14    
      ****************************************************************  
      *    VERSION                                                      
      ****************************************************************  
      * AENDERUNGEN:                                                 *  
      * AUFTRAG ! DATUM  !VER ! AENDERUNG                 ! NAME     *  
      * -------------------------------------------------------------*  
      *         !        !    !                           !          *  
      *         !        !    !                           !          *  
      *                                                              *  
      * ENDE-LOGBUCH                                                 *  
      ****************************************************************  
      *                                                                 
      *    DIESES COPY ENTHŽLT DIE INFORMATIONEN, DIE EINMAL            
      *    PRO UPRO šBERGEBEN WERDEN.                                   
      *    ALSO NICHT: DATEN, DIE PRO FUNKTION šBERGEBEN WERDEN         
      *                (IN SEPARATEN COPYS PRO FUNKTION)                
      *                                                                 
      ****************************************************************  
      *                                                                 
       01  PI-ZTKI0445.                                                 
           05  PI-ZTKI0445-FUNKTION              PIC  X(008).           
                                                                        
                                                                        
             88   PI-ZTKI0445-DRKI2422     VALUE 'DRKI2422'.            
             88   PI-ZTKI0445-DRKI2423     VALUE 'DRKI2423'.            
             88   PI-ZTKI0445-DRKI2424     VALUE 'DRKI2424'.            
             88   PI-ZTKI0445-DRKI2428     VALUE 'DRKI2428'.            
                                                                        
      *                                                                 
      ******* ENDE COPY-MEMBER **************************************   
