      *---------------------------------------------------------------*
      *    Standard fuer alle Objekte unter PVCS VM
      *            Datum      :  24.09.2007
      *            Kategorie  :  Copystrecke
      *---------------------------------------------------------------*
      *
      *---------------------------------------------------------------*
      *    Copyright (c) 2007 ATLAS Dienstleistungen f. V. GmbH
      *---------------------------------------------------------------*
      *    $Workfile:   DRKI2097.CPY  $
      *    $Revision:   2.4  $
      *
      *    $Log:   L:/mf/CPY/DRKI2097.CPv  $
      *
      *   Rev 2.4   Sep 18 2012 13:57:10   t13ex27
      *AKI00886: Host - neues Design Kundenaktualisierung-OZP Kunde
      *
      *   Rev 2.3   19 Nov 2007 09:55:10   t13ex27
      *AKL00664: Allfinanz: Anpassung Kundenaktualisierung
      *
      *   Rev 2.2   18 Nov 2007 15:20:38   t13ex27
      *No change.
      *
      *   Rev 2.1   16 Oct 2007 14:25:20   t13ex27
      *AKL00664: Allfinanz: Anpassung Kundensuche
      *
      *   Rev 2.0   24 Sep 2007 10:18:40   t13ex27
      *Archiverstellung
      *
      *---------------------------------------------------------------*
      ****************************************************************
      *    COPY-MEMBER: ZXKI0022                                     *
      *    ----------------------------------------------------------*
      *    SCHNITTSTELLE FÜR DAS UPRO ZXKI0022                       *
      *    MIT DEN DATEN, DIE EINMAL PRO UPRO ÜBERGEBEN WERDEN       *
      *    ----------------------------------------------------------*
      ****************************************************************
      *    VERSION
      ****************************************************************
      * AENDERUNGEN:                                                 *
      * AUFTRAG ! DATUM  !VER ! AENDERUNG                 ! NAME     *
      * -------------------------------------------------------------*
      * AKL00664!24.09.07!2.1 ! neu                       !I. Frenzel*
      * AKI00886!28.11.11!2.4 ! Neue Kundenaktualisierung !I. Frenzel*
      *         !        !    !                           !          *
      *         !        !    !                           !          *
      *                                                              *
      * ENDE-LOGBUCH                                                 *
      ****************************************************************
      *
      *    DIESES COPY ENTHÄLT DIE INFORMATIONEN, DIE EINMAL
      *    PRO UPRO ÜBERGEBEN WERDEN.
      *    ALSO NICHT: DATEN, DIE PRO FUNKTION ÜBERGEBEN WERDEN
      *                (IN SEPARATEN COPYS PRO FUNKTION)
      *
      ****************************************************************
      *
       01  PI-ZXKI0022.
           05  PI-ZXKI0022-FUNKTION            PIC  X(008).
               88 PI-ZXKI0022-DRKI2098              VALUE 'DRKI2098'.
               88 PI-ZXKI0022-DRKI2099              VALUE 'DRKI2099'.
               88 PI-ZXKI0022-DRKI2100              VALUE 'DRKI2100'.
               88 PI-ZXKI0022-DRKI2553              VALUE 'DRKI2553'.
               88 PI-ZXKI0022-DRKI2588              VALUE 'DRKI2588'.
               88 PI-ZXKI0022-DRKI2619              VALUE 'DRKI2619'.
