      ****************************************************************
      *    COPY-MEMBER: DRKI0061   LESE-OZP TABLE VERTRAG            *
      *    -------------------------------------------------------   *
      *    ERSTELLT: Parent                                          *
      *    DATUM:    05.11.1997                                      *
      ****************************************************************
      *    VERSION   01                                              *
      ****************************************************************
      * AENDERUNGEN:                                                 *
      * AUFTRAG ! DATUM  !VER ! AENDERUNG                 ! NAME     *
      * -------------------------------------------------------------*
      * DAISY   !05.11.97! 01 ! NEUERSTELLUNG             ! Parent   *
      *         !28.10.98! 02 ! Funktion drki0749 eingef. !   gbe    *
      *         ! 2.08.99! 01 ! Funktion DRKI0907 eingef, ! WHO      *
      * aki00055!27.10.99!    ! Funktion DRKI0648 eingef, ! Zgur-Vujic
      * apa00139!07.06.21! 04 ! Funktion DRKI1228 eingef, ! Wang     *
      * AKI00303!27.09.02!2.4 ! Funktion DRKI1448 eingef. !I.Frenzel *
      * FKI00729!08.05.03!2.5 ! Funktion DRKI1448 gel.    !I.Frenzel *
      * AKI00664!04.07.07!2.6 ! Funktion DRKI2043 eingef. !W.Schmidt *
      * AKI00664!24.09.07!2.6 ! Funktion DRKI2102 eingef. !I.Frenzel *
      *****************************************************************
      * AENDERUNGEN:
      * AUFTRAG ! DATUM  ! AENDERUNG                       ! NAME
      * ---------------------------------------------------------------
      * DBO-8361!07.04.21!FUNKTION DRKI3866 EINGEFÜGT      !T13AC20
      *         !        !                                 !
      *         !        !                                 !
      *         !        !                                 !
      *
      * ENDE-LOGBUCH

      ****************************************************************
       01  PI-ZWKI0357.
           05 PI-ZWKI0357-FUNKTION            PIC X(008).
              88 PI-ZWKI0357-DRKI0062             VALUE 'DRKI0062'.
              88 PI-ZWKI0357-DRKI0749             VALUE 'DRKI0749'.
              88 PI-ZWKI0357-DRKI0907             VALUE 'DRKI0907'.
              88 PI-ZWKI0357-DRKI0648             VALUE 'DRKI0648'.
              88 PI-ZWKI0357-DRKI1228             VALUE 'DRKI1228'.
040707        88 PI-ZWKI0357-DRKI2043             VALUE 'DRKI2043'.
240907        88 PI-ZWKI0357-DRKI2102             VALUE 'DRKI2102'.
              88 PI-ZWKI0357-DRKI3866             VALUE 'DRKI3866'.
      *
      ****************************************************************
