      *---------------------------------------------------------------*
      *    Standard für alle Objekte unter PVCS
      *            Datum   :  November 1995
      *            Kopf aus:  N:\PROFILE\KOPFCBL.DAT
      *---------------------------------------------------------------*
      *
      *---------------------------------------------------------------*
      *    Copyright 1995 ATLAS Dienstleistungs GmbH
      *---------------------------------------------------------------*
      *    $Workfile:   DRKI0240.CPY  $
      *    $Revision:   2.1  $
      *
      *    $Log:   L:/mf/CPY/DRKI0240.CPv  $
      *
      *   Rev 2.1   05 Dec 2007 10:54:36   t13ex27
      *AKL00664: Allfinanz: Mandantenprüfung bei ID-Funktionen
      *
      *   Rev 2.0   Feb 27 1999 12:54:02   P13SP20
      *NT-Umstellung
      *
      *   Rev 1.0   23 Jun 1998 13:50:34   P13SP99
      *Initial revision.
      *
      *---------------------------------------------------------------*
