      *---------------------------------------------------------------*
      *    Standard fuer alle Objekte unter PVCS VM
      *            Datum     :  26.04.2013
      *            Kategorie :  Cobol-Programm
      *---------------------------------------------------------------*
      *
      *---------------------------------------------------------------*
      *    Copyright (c) 2012 ATLAS Dienstleistungen f. V. GmbH
      *---------------------------------------------------------------*
      *    $Workfile:   DRMA4549.CPY  $
      *    $Revision:   2.2  $
      *
      *    $Log:   L:/mf/CPY/DRMA4549.CPv  $
      *
      *   Rev 2.2   Jul 22 2013 13:00:38   p13sp14
      *AMA00011: Kalypso: Teilprojekt 4
      *
      *   Rev 2.1   Jul 01 2013 17:31:58   p13sp20
      *AMA00011: Kalypso: Teilprojekt 4
      *
      *   Rev 2.0   Apr 26 2013 12:00:00   p13sp20
      *Archiverstellung
      *
      *---------------------------------------------------------------*
      **************************************************************
      *
      *     Eingabebereich UPMA4548
      *     RDz
      *     SOURCE-NAME      :  DRMA4549
      *     DMR-NAME         :  DG-OV4549
      *
      *     AUTOR            :  BOOST, MANFRED
      *     GENERIERUNG      :  17.07.2012/15:55:28
      *     LETZTE AENDERUNG :
      *
      **************************************************************
      *
      *
           05 DG-OV4549.
      *    Eingabebereich UPMA4548
              07 VG                     PIC 9(4).
      *    Vertriebsgesellschaft der DVAG
      *
      **************************************************************
