      *---------------------------------------------------------------*
      *    Standard fuer alle Objekte unter PVCS VM
      *            Datum     :  26.04.2013
      *            Kategorie :  Cobol-Programm
      *---------------------------------------------------------------*
      *
      *---------------------------------------------------------------*
      *    Copyright (c) 2012 ATLAS Dienstleistungen f. V. GmbH
      *---------------------------------------------------------------*
      *    $Workfile:   DRMA3270.CPY  $
      *    $Revision:   2.1  $
      *
      *    $Log:   L:/mf/CPY/DRMA3270.CPv  $
      *
      *   Rev 2.1   Jul 01 2013 11:45:40   p13sp20
      *AMA00011: Kalypso: Teilprojekt 4
      *
      *   Rev 2.0   Apr 26 2013 12:00:00   p13sp20
      *Archiverstellung
      *
      *---------------------------------------------------------------*
      **************************************************************
      *
      *     VB-Nummern mit Saldenabweichung im Summenblatt
      *
      *     SOURCE-NAME      :  DRMA3270
      *     DMR-NAME         :  DR-OV3270
      *
      *     AUTOR            :  WILHELM, OLIVER
      *     GENERIERUNG      :  04.05.07/13:23
      *     LETZTE AENDERUNG :
      *
      **************************************************************
      *
      *
           05 DRMA3270.
              07 VBNR                   PIC 9(9).
      *
      **************************************************************
