      *---------------------------------------------------------------*
      *    Standard fuer alle Objekte unter PVCS VM
      *            Datum      :  08.03.2012
      *            Kategorie  :  Copystrecke
      *---------------------------------------------------------------*
      *
      *---------------------------------------------------------------*
      *    Copyright (c) 2012 ATLAS Dienstleistungen f. V. GmbH
      *---------------------------------------------------------------*
      *    $Workfile:   DROK0120.CPY  $
      *    $Revision:   2.1  $
      *
      *    $Log:   L:/mf/CPY/DROK0120.CPv  $
      *
      *   Rev 2.1   May 29 2012 10:21:28   t13ex27
      *AOK00047: Auswertung Einarbeitungszeiten und Satzstatistik-D
      *B und OZPs
      *
      *   Rev 2.0   Mar 08 2012 15:46:22   t13ex27
      *Archiverstellung
      *
      *---------------------------------------------------------------*
      ****************************************************************
      * AENDERUNGEN:                                                 *
      * AUFTRAG ! DATUM  !VER ! AENDERUNG                 ! NAME     *
      * -------------------------------------------------------------*
      * AOK00047!08.03.12! 2.1! NEU                       !I. Frenzel*
      *         !        !    !                           !          *
      *         !        !    !                           !          *
      *         !        !    !                           !          *
      *                                                              *
      * ENDE-LOGBUCH                                                 *
      ****************************************************************
       01  PI-ZWOK0019.
           05 PI-ZWOK0019-FUNKTION            PIC X(008).
              88 PI-ZWOK0019-DROK0121             VALUE 'DROK0121'.
      ********************** Datenende ********************************
