      *---------------------------------------------------------------*
      *    Standard fuer alle Objekte unter PVCS VM
      *            Datum      :  03.07.2015
      *            Kategorie  :  Copystrecke
      *---------------------------------------------------------------*
      *    Copyright (c) 2015 ATLAS Dienstleistungen f. V. GmbH
      *---------------------------------------------------------------*
      *    $Workfile:   DRPA1823.CPY  $
      *    $Revision:   2.1  $
      *
      *    $Log:   L:/mf/CPY/DRPA1823.CPv  $
      *
      *   Rev 2.1   Jul 03 2015 10:37:58   T13AE37
      *APA01932: ABU / Schnittstellen und Referenz
      *
      *   Rev 2.0   Jul 03 2015 09:17:00   T13AE37
      *Archiverstellung
      *
      *---------------------------------------------------------------*
      ****************************************************************
      * AENDERUNGEN:                                                 *
      * AUFTRAG ! DATUM  !VER ! AENDERUNG                 ! NAME     *
      * -------------------------------------------------------------*
      * APA01932!03.07.15!2.1 ! NEUERSTELLUNG             ! BUCH     *
      *         !        !    !                           !          *
      *                                                              *
      * ENDE-LOGBUCH                                                 *
      ****************************************************************
      *                                                              *
      *    DIESES COPY ENTHÄLT DIE FUNKTIONEN FÜR DAS QSAM-OZP       *
      *    ZIPA0138                                                  *
      *                                                              *
      ****************************************************************
      *
       01  PI-ZIPA0138.
           05 PI-ZIPA0138-FUNKTION            PIC X(008).
              88 PI-ZIPA0138-DRPA1824             VALUE 'DRPA1824'.
      ***** ENDE-COPY-MEMBER *****************************************

