      *---------------------------------------------------------------*
      *    Standard für alle Objekte unter PVCS
      *            Datum   :  Januar 1999
      *            Kopf aus:  N:\PROFILE\KOPFCPY.DAT
      *---------------------------------------------------------------*
      *
      *---------------------------------------------------------------*
      *    Copyright 1999 ATLAS Dienstleistungs GmbH
      *---------------------------------------------------------------*
      *    $Workfile:   DRPA1400.CPY  $
      *    $Revision:   2.1  $
      *
      *    $Log:   L:\MF\CPY\DRPA1400.CPv  $
      *
      *   Rev 2.1   07 Sep 2000 14:56:22   T13EX23
      *APA00096 - Neuerstellung
      *
      *   Rev 2.0   Apr 11 2000 16:58:12   P13SP20
      *Archiverstellung
      *
      *---------------------------------------------------------------*
      *****************************************************************
      *    COPY-MEMBER: DRPA1400                                      *
      *    --------------------------------------------------------   *
      *    SCHNITTSTELLE FÜR DAS GESAMTSTEUERUNG SB UPPA0093          *
      *    --------------------------------------------------------   *
      *    ERSTELLT: GRAY                                             *
      *    DATUM:    19.07.2000                                       *
      *****************************************************************
      *    VERSION
      *****************************************************************
      * AENDERUNGEN:                                                  *
      * AUFTRAG ! DATUM  !VER ! AENDERUNG                 ! NAME      *
      * --------------------------------------------------------------*
      * APA00090!19.07.00! 2.1! NEUERSTELLUNG             ! GRAY      *
      *         !        !    !                           !           *
      *         !        !    !                           !           *
      *         !        !    !                           !           *
      *                                                               *
      * ENDE-LOGBUCH                                                  *
      *****************************************************************
      *
      *    DIESES COPY ENTHÄLT DIE INFORMATIONEN, DIE EINMAL
      *    PRO UPRO ÜBERGEBEN WERDEN.
      *    ALSO NICHT: DATEN, DIE PRO FUNKTION ÜBERGEBEN WERDEN
      *                (IN SEPARATEN COPYS PRO FUNKTION)
      *
      ****************************************************************
      *
       01  PI-UPPA0093.
           05  PI-UPPA0093-FUNKTION            PIC  X(008).
               88 PI-UPPA0093-DRPA1407              VALUE 'DRPA1407'.
               88 PI-UPPA0093-DRPA1416              VALUE 'DRPA1416'.

      ******* ENDE COPY-MEMBER **************************************
