      *---------------------------------------------------------------*
      *    STANDARD FÜR ALLE OBJEKTE UNTER PVCS
      *     DATUM   :  NOVEMBER 1995
      *     KOPF AUS:  N:PROFILEKOPFCBL.DAT
      *---------------------------------------------------------------*
      *
      *---------------------------------------------------------------*
      *    COPYRIGHT 1995 ATLAS DIENSTLEISTUNGS GMBH
      *---------------------------------------------------------------*
      *    $Workfile:   DRPA0040.CPY  $
      *    $Revision:   2.0  $
      *
      *    $Log:   L:\MF\CPY\DRPA0040.CPv  $
      *
      *   Rev 2.0   Feb 27 1999 14:27:24   P13SP20
      *NT-Umstellung
      *
      *   Rev 1.1   Mar 06 1997 14:50:26   P13PVCS
      *Neuerstellung
      *
      *---------------------------------------------------------------*
      ****************************************************************
      *    COPY-MEMBER: DRPA0040  FUNKTIONEN STANDARD-OZP            *
      *                           PDTA TBPA0017                      *
      *                                                              *
      *    -------------------------------------------------------   *
      *    ERSTELLT: PRÖMPELER                                       *
      *    DATUM:    20.08.1996                                      *
      ****************************************************************
      *    VERSION   01
      ****************************************************************
      * AENDERUNGEN:                                                 *
      * AUFTRAG ! DATUM  !VER ! AENDERUNG                 ! NAME     *
      * -------------------------------------------------------------*
      * DAISY 1 !19.08.96! 01 ! NEUERSTELLUNG             ! PRÖMPELER*
      *         !        !    !                           !          *
      *         !        !    !                           !          *
      *         !        !    !                           !          *
      *                                                              *
      * ENDE-LOGBUCH                                                 *
      ****************************************************************
       01  PI-ZTPA0017.
           03 PI-ZTPA0017-FUNKTION            PIC X(008).
              88 PI-ZTPA0017-DRPA0094-INS         VALUE 'DRPA0094'.
              88 PI-ZTPA0017-DRPA0095-UPD         VALUE 'DRPA0095'.
              88 PI-ZTPA0017-DRPA0096-DEL         VALUE 'DRPA0096'.
              88 PI-ZTPA0017-DRPA0097-SEL-ALL     VALUE 'DRPA0097'.
