      *---------------------------------------------------------------*
      *    Standard f?r alle Objekte unter PVCS
      *            Datum   :  November 1995
      *            Kopf aus:  N:\PROFILE\KOPFCBL.DAT
      *---------------------------------------------------------------*
      *
      *---------------------------------------------------------------*
      *    Copyright 1995 ATLAS Dienstleistungs GmbH
      *---------------------------------------------------------------*
      *    $Workfile:   DRPA0690.CPY  $
      *    $Revision:   2.4  $
      *
      *    $Log:   L:/mf/CPY/DRPA0690.CPv  $
      *
      *   Rev 2.4   Oct 12 2004 08:11:00   t13ex44
      *APA00218: Auslagerung von Provisionsdaten
      *
      *   Rev 2.3   Apr 16 2002 14:59:02   T13ex22
      *FPA00346: Änderungen für CRPA0108
      *
      *   Rev 2.2   May 27 1999 15:07:42   T13EX26
      *MFE-Umstellung 2
      *
      *   Rev 2.1   May 27 1999 13:18:18   T13EX26
      *MFE-Umstellung
      *
      *
      *   Rev 2.0   May 26 1999 16:57:58   T13EX26
      *MFE-Umstellung
      *
      *   Rev 1.0   11 Nov 1997 17:00:26   P13SP99
      *Initial revision.
      *
      *---------------------------------------------------------------*
      ****************************************************************
      *    COPY-MEMBER: DRPA0690  FUNKTIONSAUFRUFE FÜR ZXPA0117      *
      *    -------------------------------------------------------   *
      *    ERSTELLT: PARENT                                          *
      *    DATUM:    09.12.1997                                      *
      ****************************************************************
      *    VERSION   01                                              *
      ****************************************************************
      * AENDERUNGEN:                                                 *
      * AUFTRAG ! DATUM  !VER ! AENDERUNG                 ! NAME     *
      * -------------------------------------------------------------*
      * AFPA0012!09.12.97! 01  !NEUERSTELLUNG             ! PARENT   *
      * AFPA0012!08.07.98!01.02!NEUE FUNKTION DRPA1007    !BOHLINGER *
      * FPA00346!11.03.02!02.01!NEUE FUNKTION DRPA1527    ! MUND     *
      * FPA00346!11.03.02!02.01!NEUE FUNKTION DRPA1528    ! MUND     *
      * APA00218!15.07.04!02.04!NEUE FUNKTION DRPA1620    ! SCHEIDEL *
      *                                                              *
      * ENDE-LOGBUCH                                                 *
      ****************************************************************
      *
       01  PI-ZXPA0117.
           05  PI-ZXPA0117-FUNKTION            PIC  X(008).
               88 PI-ZXPA0117-DRPA0692              VALUE 'DRPA0692'.
               88 PI-ZXPA0117-DRPA1007              VALUE 'DRPA1007'.
               88 PI-ZXPA0117-DRPA1527              VALUE 'DRPA1527'.
               88 PI-ZXPA0117-DRPA1528              VALUE 'DRPA1528'.
               88 PI-ZXPA0117-DRPA1620              VALUE 'DRPA1620'.
