      *---------------------------------------------------------------*
      *    Standard für alle Objekte unter PVCS
      *            Datum   :  November 1995
      *            Kopf aus:  N:\PROFILE\KOPFCBL.DAT
      *---------------------------------------------------------------*
      *
      *---------------------------------------------------------------*
      *    Copyright 1995 ATLAS Dienstleistungs GmbH
      *---------------------------------------------------------------*
      *    $Workfile:   DRPA0890.CPY  $
      *    $Revision:   2.1  $
      *
      *    $Log:   L:\MF\CPY\DRPA0890.CPv  $
      *
      *   Rev 2.1   Jan 18 2000 14:37:36   T13EX22
      *APA00071: SF44 mit TBPA0026-Zugriff
      *
      *   Rev 2.0   Feb 27 1999 14:29:48   P13SP20
      *NT-Umstellung
      *
      *   Rev 1.0   14 Jan 1998 12:49:02   P13SP99
      *Initial revision.
      *
      *----------------------------------------------------------------*
      *******************************************************************
      *    COPY-MEMBER: DRPA0032  FUNKTIONEN STANDARD-OZP
      *                           PGTA TBPA0026
      *
      *    --------------------------------------------------------
      *    ERSTELLT: MUND
      *    DATUM:    18.11.1999
      ******************************************************************
      *    VERSION   01
      ****************************************************************
      * AENDERUNGEN:
      * AUFTRAG ! DATUM  !VER ! AENDERUNG                 ! NAME
      * -------------------------------------------------------------
      * APA00071!18.11.99! 01 ! NEUERSTELLUNG             ! MUND
      *         !        !    !                           !
      *         !        !    !                           !
      *         !        !    !                           !
      *
      * ENDE-LOGBUCH
      ****************************************************************
       01  PI-ZTPA0026.
           05 PI-ZTPA0026-FUNKTION            PIC X(008).
              88 PI-ZTPA0026-DRPA0897-INS         VALUE 'DRPA0897'.
              88 PI-ZTPA0026-DRPA0919-UPD         VALUE 'DRPA0919'.
              88 PI-ZTPA0026-DRPA0920-DEL         VALUE 'DRPA0920'.
              88 PI-ZTPA0026-DRPA0921-SEL-ALL     VALUE 'DRPA0921'.
              88 PI-ZTPA0026-DRPA1323-BEEND       VALUE 'DRPA1323'.

