      *---------------------------------------------------------------*
      *    Standard fuer alle Objekte unter PVCS VM
      *            Datum      :  09.03.2015
      *            Kategorie  :  Copystrecke
      *---------------------------------------------------------------*
      *    Copyright (c) 2015 ATLAS Dienstleistungen f. V. GmbH
      *---------------------------------------------------------------*
      *    $Workfile:   DRKI2990.CPY  $
      *    $Revision:   2.1  $
      *
      *    $Log:   L:/mf/CPY/DRKI2990.CPv  $
      *
      *   Rev 2.1   Mar 12 2015 13:32:50   t13ex15
      *AKI01337: Änderung KLU Sonderleistungen 2015 Anpassung VBI S
      *ST und AS-Club
      *
      *   Rev 2.0   Mar 09 2015 14:00:14   t13ex15
      *Archiverstellung
      *
      *---------------------------------------------------------------*
       01  PI-ZXKI0465.
           05 PI-ZXKI0465-FUNKTION            PIC X(008).
              88 PI-ZXKI0465-DRKI2991-LIST        VALUE 'DRKI2991'.



