      *---------------------------------------------------------------*
      *    Standard fuer alle Objekte unter PVCS VM
      *            Datum      :  10.12.2013
      *            Kategorie  :  Copystrecke
      *---------------------------------------------------------------*
      *
      *---------------------------------------------------------------*
      *    Copyright (c) 2015 ATLAS Dienstleistungen f. V. GmbH
      *---------------------------------------------------------------*
      *    $Workfile:   DRKI2820.CPY  $
      *    $Revision:   2.3  $
      *
      *    $Log:   L:/mf/CPY/DRKI2820.CPv  $
      *
      *   Rev 2.3   Jun 17 2015 10:02:04   t13ex27
      *FKI01501: EVM-KZ anpassen bei KdBv
      *
      *   Rev 2.2   Apr 16 2014 17:11:48   t13ex19
      *AKI01269: Tabelle DBPRODUKT -> Analog OKI.Kreditkarten_Eigen
      *
      *   Rev 2.1   Jan 14 2014 13:15:34   i13az40
      *AKI01269: Tabelle DBPRODUKT -> Analog OKI.Kreditkarten_Eigen
      *
      *   Rev 2.0   Dec 10 2013 16:12:22 I13AZ40
      *Archiverstellung
      *
      *---------------------------------------------------------------*
      ****************************************************************
      *    COPY-MEMBER: DRKI2820                                     *
      *    ----------------------------------------------------------*
      *    SCHNITTSTELLE FÜR DAS UPRO ZTKI0466                       *
      *    MIT DEN DATEN, DIE EINMAL PRO UPRO ÜBERGEBEN WERDEN       *
      *    ----------------------------------------------------------*
      ****************************************************************
      *   ERZEUGT MIT OZPGEN         15.06.2015 / 12:00:01 / T13EX27
      ****************************************************************
      *    VERSION
      ****************************************************************
      * AENDERUNGEN:                                                 *
      * AUFTRAG ! DATUM  !VER ! AENDERUNG                 ! NAME     *
      * -------------------------------------------------------------*
      *         !        !    !                           !          *
      *         !        !    !                           !          *
      *                                                              *
      * ENDE-LOGBUCH                                                 *
      ****************************************************************
      *
      *    DIESES COPY ENTHÄLT DIE INFORMATIONEN, DIE EINMAL
      *    PRO UPRO ÜBERGEBEN WERDEN.
      *    ALSO NICHT: DATEN, DIE PRO FUNKTION ÜBERGEBEN WERDEN
      *                (IN SEPARATEN COPYS PRO FUNKTION)
      *
      ****************************************************************
      *
       01  PI-ZTKI0466.
           05  PI-ZTKI0466-FUNKTION              PIC  X(008).


             88   PI-ZTKI0466-DRKI2821     VALUE 'DRKI2821'.
             88   PI-ZTKI0466-DRKI2822     VALUE 'DRKI2822'.
             88   PI-ZTKI0466-DRKI2823     VALUE 'DRKI2823'.
             88   PI-ZTKI0466-DRKI2824     VALUE 'DRKI2824'.
             88   PI-ZTKI0466-DRKI2825     VALUE 'DRKI2825'.
             88   PI-ZTKI0466-DRKI2826     VALUE 'DRKI2826'.
             88   PI-ZTKI0466-DRKI3013     VALUE 'DRKI3013'.

      *
      ******* ENDE COPY-MEMBER **************************************

