      *---------------------------------------------------------------* 
      *    Standard fuer alle Objekte unter PVCS VM                     
      *            Datum      :  20.09.2010                             
      *            Kategorie  :  Copystrecke                            
      *---------------------------------------------------------------* 
      *                                                                 
      *---------------------------------------------------------------* 
      *    Copyright (c) 2010 ATLAS Dienstleistungen f. V. GmbH         
      *---------------------------------------------------------------* 
      *    $Workfile:   DRKI2418.CPY  $                                      

      *    $Revision:   2.1  $                                          
      *                                                                 
      *    $Log:   L:/mf/CPY/DRKI2418.CPv  $                             
      *
      *   Rev 2.1   Sep 29 2010 10:50:04   t13ex14
      *AKI00966: DVAG Österreich: DB-Objekte
      *                                                                 
      *   Rev 2.0   Sep 20 2010 13:39:48 T13EX27                        
      *Archiverstellung                                                 
      *                                                                 
      *---------------------------------------------------------------* 
      ****************************************************************  
      *    COPY-MEMBER: DRKI2418                                     *  
      *    ----------------------------------------------------------*  
      *    SCHNITTSTELLE FÜR DAS UPRO ZTKI0032                       *
      *    MIT DEN DATEN, DIE EINMAL PRO UPRO ÜBERGEBEN WERDEN       *
      *    ----------------------------------------------------------*  
      ****************************************************************  
      *   ERZEUGT MIT OZPGEN         20.09.2010 / 13:39:48 / T13EX27    
      ****************************************************************  
      *    VERSION                                                      
      ****************************************************************  
      * AENDERUNGEN:                                                 *  
      * AUFTRAG ! DATUM  !VER ! AENDERUNG                 ! NAME     *  
      * -------------------------------------------------------------*  
      *         !        !    !                           !          *  
      *         !        !    !                           !          *  
      *                                                              *  
      * ENDE-LOGBUCH                                                 *  
      ****************************************************************  
      *                                                                 
      *    DIESES COPY ENTHÄLT DIE INFORMATIONEN, DIE EINMAL
      *    PRO UPRO ÜBERGEBEN WERDEN.
      *    ALSO NICHT: DATEN, DIE PRO FUNKTION ÜBERGEBEN WERDEN
      *                (IN SEPARATEN COPYS PRO FUNKTION)                
      *                                                                 
      ****************************************************************  
      *                                                                 
       01  PI-ZTKI0032.                                                 
           05  PI-ZTKI0032-FUNKTION              PIC  X(008).           
                                                                        
                                                                        
             88   PI-ZTKI0032-DRKI2419     VALUE 'DRKI2419'.            
             88   PI-ZTKI0032-DRKI2420     VALUE 'DRKI2420'.            
                                                                        
      *                                                                 
      ******* ENDE COPY-MEMBER **************************************   
