      ****************************************************************          
      *    COPY-MEMBER: DRKI3965                                     *          
      *    ----------------------------------------------------------*          
      *    SCHNITTSTELLE FÜR DAS UPRO ZTKI0562                       *          
      *    MIT DEN DATEN, DIE EINMAL PRO UPRO ÜBERGEBEN WERDEN       *          
      *    ----------------------------------------------------------*          
      ****************************************************************          
      *   ERZEUGT MIT OZPGEN         06.09.2022 / 08:45:46 / T13AC20            
      ****************************************************************          
      *    VERSION                                                              
      ****************************************************************          
      * AENDERUNGEN:                                                 *          
      * AUFTRAG ! DATUM  !VER ! AENDERUNG                 ! NAME     *          
      * -------------------------------------------------------------*          
      *         !        !    !                           !          *          
      *         !        !    !                           !          *          
      *                                                              *          
      * ENDE-LOGBUCH                                                 *          
      ****************************************************************          
      *                                                                         
      *    DIESES COPY ENTHÄLT DIE INFORMATIONEN, DIE EINMAL                    
      *    PRO UPRO ÜBERGEBEN WERDEN.                                           
      *    ALSO NICHT: DATEN, DIE PRO FUNKTION ÜBERGEBEN WERDEN                 
      *                (IN SEPARATEN COPYS PRO FUNKTION)                        
      *                                                                         
      ****************************************************************          
      *                                                                         
       01  PI-ZTKI0562.                                                         
           05  PI-ZTKI0562-FUNKTION              PIC  X(008).                   
                                                                                
                                                                                
             88   PI-ZTKI0562-DRKI3966     VALUE 'DRKI3966'.                    
             88   PI-ZTKI0562-DRKI3967     VALUE 'DRKI3967'.                    
             88   PI-ZTKI0562-DRKI3968     VALUE 'DRKI3968'.                    
             88   PI-ZTKI0562-DRKI3969     VALUE 'DRKI3969'.                    
                                                                                
      *                                                                         
      ******* ENDE COPY-MEMBER **************************************           
