      *---------------------------------------------------------------*
      *    Standard fuer alle Objekte unter PVCS VM
      *            Datum      :  11.01.2008
      *            Kategorie  :  Copystrecke
      *---------------------------------------------------------------*
      *
      *---------------------------------------------------------------*
      *    Copyright (c) 2008 ATLAS Dienstleistungen f. V. GmbH
      *---------------------------------------------------------------*
      *    $Workfile:   DRKI2226.CPY  $
      *    $Revision:   2.3  $
      *
      *    $Log:   L:/mf/CPY/DRKI2226.CPv  $
      *
      *   Rev 2.3   Jun 05 2012 11:08:26   t13ex19
      *AKI01124: Erweiterung VBI-SST STVD0060
      *
      *   Rev 2.2   Jun 05 2012 09:49:16   t13ex19
      *AKI01124: Erweiterung VBI-SST STVD0060
      *
      *   Rev 2.1   Jan 11 2008 18:28:04   t13ex51
      *AKL00664: Allfinanz: VBI-Schnittstelle
      *
      *   Rev 2.0   Jan 11 2008 11:17:36   t13ex51
      *Archiverstellung
      *
      *---------------------------------------------------------------*
      ****************************************************************
      *    COPY-MEMBER: DRKI2226  FUNKTIONEN LIST-OZP                *
      *                                                              *
      *                                                              *
      *    -------------------------------------------------------   *
      *    ERSTELLT: HRO                                             *
      *    DATUM:    11.01.2008                                      *
      ****************************************************************
      *    VERSION   01
      ****************************************************************
      * AENDERUNGEN:                                                 *
      * AUFTRAG ! DATUM  !VER ! AENDERUNG                 ! NAME     *
      * -------------------------------------------------------------*
      * AKL00664!05.10.07! 01 ! NEUERSTELLUNG             ! HRO      *
      *         !        !    !                           !          *
      * AKI01124!13.03.12!    ! Neue Funktion             ! BST      *
      *         !        !    !                           !          *
      * ENDE-LOGBUCH                                                 *
      ****************************************************************
       01  PI-ZXKI0407.
           05 PI-ZXKI0407-FUNKTION             PIC X(008).
              88 PI-ZXKI0407-DRKI2227             VALUE 'DRKI2227'.
              88 PI-ZXKI0407-DRKI2573             VALUE 'DRKI2573'.


