      ****************************************************************          
      *    COPY-MEMBER: DRKI3146                                     *          
      *    ----------------------------------------------------------*          
      *    SCHNITTSTELLE FÜR DAS UPRO ZTKI0561                       *          
      *    MIT DEN DATEN, DIE EINMAL PRO UPRO ÜBERGEBEN WERDEN       *          
      *    ----------------------------------------------------------*          
      ****************************************************************          
      *   ERZEUGT MIT OZPGEN         24.08.2022 / 10:44:29 / T13AC20            
      ****************************************************************          
      *    VERSION                                                              
      ****************************************************************          
      * AENDERUNGEN:                                                 *          
      * AUFTRAG ! DATUM  !VER ! AENDERUNG                 ! NAME     *          
      * -------------------------------------------------------------*          
      *         !        !    !                           !          *          
      *         !        !    !                           !          *          
      *                                                              *          
      * ENDE-LOGBUCH                                                 *          
      ****************************************************************          
      *                                                                         
      *    DIESES COPY ENTHÄLT DIE INFORMATIONEN, DIE EINMAL                    
      *    PRO UPRO ÜBERGEBEN WERDEN.                                           
      *    ALSO NICHT: DATEN, DIE PRO FUNKTION ÜBERGEBEN WERDEN                 
      *                (IN SEPARATEN COPYS PRO FUNKTION)                        
      *                                                                         
      ****************************************************************          
      *                                                                         
       01  PI-ZTKI0561.                                                         
           05  PI-ZTKI0561-FUNKTION              PIC  X(008).                   
                                                                                
                                                                                
             88   PI-ZTKI0561-DRKI3528     VALUE 'DRKI3528'.                    
             88   PI-ZTKI0561-DRKI3529     VALUE 'DRKI3529'.                    
             88   PI-ZTKI0561-DRKI3530     VALUE 'DRKI3530'.                    
             88   PI-ZTKI0561-DRKI3531     VALUE 'DRKI3531'.                    
                                                                                
      *                                                                         
      ******* ENDE COPY-MEMBER **************************************           
