      *---------------------------------------------------------------*         
      *    Standard für alle Objekte unter PVCS                                 
      *            Datum   :  Mai 2002                                          
      *            Kopf aus:  N:\PROFILE\KOPFCPY.DAT                            
      *---------------------------------------------------------------*         
      *                                                                         
      *---------------------------------------------------------------*         
      *    Copyright (c) 2021 ATLAS Dienstleistungen f. V. GmbH                 
      *---------------------------------------------------------------*         
      *    $Workfile:   DRKI1487.CPY  $                                         
      *    $Revision:   2.8  $                                                  
      *                                                                         
      *    $Log:   L:/mf/CPY/DRKI1487.CPv  $                                    
      *                                                                         
      *   Rev 2.8   Jan 21 2021 17:04:30   u130685                              
      *AKI01821: Guthabenzahlung COPY                                           
      *                                                                         
      *   Rev 2.7   Jan 20 2021 14:08:04   u130685                              
      *AKI01821: Guthabenzahlung COPY                                           
      *                                                                         
      *   Rev 2.4   Aug 20 2009 15:23:42   t13ex50                              
      *AKI00844: DWS-Investmentsparpläne                                        
      *                                                                         
      *   Rev 2.0   Oct 16 2002 08:32:30   p13sp16                              
      *Archiverstellung                                                         
      *                                                                         
      *---------------------------------------------------------------*         
      ****************************************************************          
      *    COPY-MEMBER: DRKI1487                                     *          
      *    ----------------------------------------------------------*          
      *    SCHNITTSTELLE FÜR DAS UPRO ZTKI0316                       *          
      *    MIT DEN DATEN, DIE EINMAL PRO UPRO ÜBERGEBEN WERDEN       *          
      *    ----------------------------------------------------------*          
      ****************************************************************          
      *   ERZEUGT MIT OZPGEN         16.08.2021 / 15:39:32 / T13EX39            
      ****************************************************************          
      *    VERSION                                                              
      ****************************************************************          
      * AENDERUNGEN:                                                 *          
      * AUFTRAG ! DATUM  !VER ! AENDERUNG                 ! NAME     *          
      * -------------------------------------------------------------*          
      *         !        !    !                           !          *          
      *         !        !    !                           !          *          
      *                                                              *          
      * ENDE-LOGBUCH                                                 *          
      ****************************************************************          
      *                                                                         
      *    DIESES COPY ENTHÄLT DIE INFORMATIONEN, DIE EINMAL                    
      *    PRO UPRO ÜBERGEBEN WERDEN.                                           
      *    ALSO NICHT: DATEN, DIE PRO FUNKTION ÜBERGEBEN WERDEN                 
      *                (IN SEPARATEN COPYS PRO FUNKTION)                        
      *                                                                         
      ****************************************************************          
      *                                                                         
       01  PI-ZTKI0316.                                                         
           05  PI-ZTKI0316-FUNKTION              PIC  X(008).                   
                                                                                
                                                                                
             88   PI-ZTKI0316-DRKI1492     VALUE 'DRKI1492'.                    
             88   PI-ZTKI0316-DRKI2352     VALUE 'DRKI2352'.                    
             88   PI-ZTKI0316-DRKI2353     VALUE 'DRKI2353'.                    
             88   PI-ZTKI0316-DRKI2354     VALUE 'DRKI2354'.                    
             88   PI-ZTKI0316-DRKI3896     VALUE 'DRKI3896'.                    
                                                                                
      *                                                                         
      ******* ENDE COPY-MEMBER **************************************           
