      *---------------------------------------------------------------*
      *    Standard fuer alle Objekte unter PVCS VM
      *            Datum      :  27.09.2013
      *            Kategorie  :  Copystrecke
      *---------------------------------------------------------------*
      *
      *---------------------------------------------------------------*
      *    Copyright (c) 2013 ATLAS Dienstleistungen f. V. GmbH
      *---------------------------------------------------------------*
      *    $Workfile:   DRKI2787.CPY  $
      *    $Revision:   2.2  $
      *
      *    $Log:   L:/mf/CPY/DRKI2787.CPv  $
      *
      *   Rev 2.2   Apr 04 2014 11:25:14   T13Ex77
      *FKI01460: Fehlerdateien und Fehlermails DWS
      *
      *   Rev 2.1   Mar 11 2014 15:48:22   t13ex77
      *AKI01269: Tabelle DBPRODUKT -> Analog OKI.Kreditkarten_Eigen
      *
      *   Rev 2.0   Sep 27 2013 10:52:14   t13ex77
      *Archiverstellung
      *
      *---------------------------------------------------------------*
       01  PI-UPKI0245.
           05 PI-UPKI0245-FUNKTION              PIC X(008).
              88 PI-UPKI0245-DRKI2789             VALUE 'DRKI2789'.

