      *---------------------------------------------------------------*
      *    Standard fuer alle Objekte unter PVCS VersionManager
      *            Datum      :  20.05.2020
      *            Kategorie  :  Copystrecke
      *---------------------------------------------------------------*
      *    Copyright (c) 2020 ATLAS Dienstleistungen f. V. GmbH
      *---------------------------------------------------------------*
      *    $Workfile:   DRKI3791.CPY  $
      *    $Revision:   2.1  $
      *
      *    $Log:   L:/mf/CPY/DRKI3791.CPv  $
      *
      *   Rev 2.1   Jul 07 2020 13:01:22   t13ex78
      *AKI01780: Programme und Copies
      *
      *   Rev 2.0   May 20 2020 09:00:12   t13ex78
      *Archiverstellung
      *
      *---------------------------------------------------------------*

