      ****************************************************************          
      *    COPY-MEMBER: DRKI3955                                     *          
      *    ----------------------------------------------------------*          
      *    SCHNITTSTELLE FÜR DAS UPRO ZTKI0559                       *          
      *    MIT DEN DATEN, DIE EINMAL PRO UPRO ÜBERGEBEN WERDEN       *          
      *    ----------------------------------------------------------*          
      ****************************************************************          
      *   ERZEUGT MIT OZPGEN         13.09.2022 / 14:40:47 / U131774            
      ****************************************************************          
      *    VERSION                                                              
      ****************************************************************          
      * AENDERUNGEN:                                                 *          
      * AUFTRAG ! DATUM  !VER ! AENDERUNG                 ! NAME     *          
      * -------------------------------------------------------------*          
      *         !        !    !                           !          *          
      *         !        !    !                           !          *          
      *                                                              *          
      * ENDE-LOGBUCH                                                 *          
      ****************************************************************          
      *                                                                         
      *    DIESES COPY ENTHÄLT DIE INFORMATIONEN, DIE EINMAL                    
      *    PRO UPRO ÜBERGEBEN WERDEN.                                           
      *    ALSO NICHT: DATEN, DIE PRO FUNKTION ÜBERGEBEN WERDEN                 
      *                (IN SEPARATEN COPYS PRO FUNKTION)                        
      *                                                                         
      ****************************************************************          
      *                                                                         
       01  PI-ZTKI0559.                                                         
           05  PI-ZTKI0559-FUNKTION              PIC  X(008).                   
                                                                                
                                                                                
             88   PI-ZTKI0559-DRKI3951     VALUE 'DRKI3951'.                    
             88   PI-ZTKI0559-DRKI3952     VALUE 'DRKI3952'.                    
             88   PI-ZTKI0559-DRKI3953     VALUE 'DRKI3953'.                    
             88   PI-ZTKI0559-DRKI3954     VALUE 'DRKI3954'.                    
                                                                                
      *                                                                         
      ******* ENDE COPY-MEMBER **************************************           
