      *---------------------------------------------------------------*
      *    Standard für alle Objekte unter PVCS
      *            Datum   :  Januar 2001
      *            Kopf aus:  N:\PROFILE\KOPFCPY.DAT
      *---------------------------------------------------------------*
      *
      *---------------------------------------------------------------*
      *    Copyright 2001 ATLAS Dienstleistungs GmbH
      *---------------------------------------------------------------*
      *    $Workfile:   DRKI1383.CPY  $
      *    $Revision:   2.1  $
      *
      *    $Log:   L:/mf/cpy/DRKI1383.CPv  $
      *
      *   Rev 2.1   Jul 30 2002 13:39:34   t13ex39
      *AKI00274 DB/24
      *
      *   Rev 2.0   Apr 09 2002 08:31:54   p13sp16
      *Archiverstellung
      *
      *---------------------------------------------------------------*
      *****************************************************************
      *    COPY-MEMBER: ZTKI0816                                      *
      *    --------------------------------------------------------   *
      *    SCHNITTSTELLE FšR DAS UPRO ZTKI0816                        *
      *    MIT DEN DATEN, DIE EINMAL PRO UPRO šBERGEBEN WERDEN        *
      *    --------------------------------------------------------   *
      ****************************************************************
      *   erzeugt mit genOZP - (c) PMSmicado  17.04.2002/12:30:36
      *****************************************************************
      *    VERSION
      ****************************************************************
      * AENDERUNGEN:                                                 *
      * AUFTRAG ! DATUM  !VER ! AENDERUNG                 ! NAME     *
      * -------------------------------------------------------------*
      *         !        !    !                           !          *
      *         !        !    !                           !          *
      *                                                              *
      * ENDE-LOGBUCH                                                 *
      ****************************************************************
      *
      *    DIESES COPY ENTHŽLT DIE INFORMATIONEN, DIE EINMAL
      *    PRO UPRO šBERGEBEN WERDEN.
      *    ALSO NICHT: DATEN, DIE PRO FUNKTION šBERGEBEN WERDEN
      *                (IN SEPARATEN COPYS PRO FUNKTION)
      *
      ****************************************************************
      *
       01  PI-ZTKI0816.
           05  PI-ZTKI0816-FUNKTION            PIC  X(008).


             88   PI-ZTKI0816-DRKI1387     VALUE 'DRKI1387'.
             88   PI-ZTKI0816-DRKI1385     VALUE 'DRKI1385'.
             88   PI-ZTKI0816-DRKI1386     VALUE 'DRKI1386'.
             88   PI-ZTKI0816-DRKI1384     VALUE 'DRKI1384'.

      *
      ******* ENDE COPY-MEMBER **************************************
