      *---------------------------------------------------------------*
      *    Standard für alle Objekte unter PVCS                       *
      *            Datum   :  November 1995                           *
      *            Kopf aus:  N:\PROFILE\KOPFCBL.DAT                  *
      *---------------------------------------------------------------*
      *                                                               *
      *---------------------------------------------------------------*
      *    Copyright 1995 ATLAS Dienstleistungs GmbH                  *
      *---------------------------------------------------------------*
      *    $Workfile:   DRPA1027.CPY  $                               *
      *    $Revision:   2.0  $                                        *
      *                                                               *
      *    $Log:   L:\MF\CPY\DRPA1027.CPv  $                          *
      *
      *   Rev 2.0   May 26 1999 13:42:26   T13EX21
      *APA00012 - Neuerstellung
      *                                                               *
      *   Rev 1.0   14 Jul 1998 13:59:44   P13SP19                    *
      *Initial revision.                                              *
      *                                                               *
      *---------------------------------------------------------------*
      *****************************************************************
      *    COPY-MEMBER: DRPA1027                                      *
      *    --------------------------------------------------------   *
      *    SCHNITTSTELLE FÜR DAS UPRO UPPA0105                        *
      *    --------------------------------------------------------   *
      *    ERSTELLT: FOLTZ                                            *
      *    DATUM:    23.07.1998                                       *
      *****************************************************************
      *    VERSION                                                    *
      ****************************************************************
      * AENDERUNGEN:                                                 *
      * AUFTRAG ! DATUM  !VER ! AENDERUNG                 ! NAME     *
      * -------------------------------------------------------------*
      * AFPA0012!23.07.98! 01 ! NEU                       ! FOLTZ    *
      *         !        !    !                           !          *
      *                                                              *
      * ENDE-LOGBUCH                                                 *
      ****************************************************************
      *
      *    DIESES COPY ENTHÄLT DIE INFORMATIONEN, DIE EINMAL
      *    PRO UPRO ÜBERGEBEN WERDEN.
      *    ALSO NICHT: DATEN, DIE PRO FUNKTION ÜBERGEBEN WERDEN
      *                (IN SEPARATEN COPYS PRO FUNKTION)
      *
      ****************************************************************
      *
       01  PI-UPPA0105.
           05 PI-UPPA0105-FUNKTION            PIC  X(008).
              88 PI-UPPA0105-DRPA1028              VALUE 'DRPA1028'.
      *
      ******* ENDE COPY-MEMBER **************************************
