      *---------------------------------------------------------------*
      *    Standard f?r alle Objekte unter PVCS
      *            Datum   :  November 1995
      *            Kopf aus:  N:\PROFILE\KOPFCBL.DAT
      *---------------------------------------------------------------*
      *
      *---------------------------------------------------------------*
      *    Copyright 1995 ATLAS Dienstleistungs GmbH
      *---------------------------------------------------------------*
      *    $Workfile:   DRPA0367.CPY  $
      *    $Revision:   2.1  $
      *
      *    $Log:   L:\MF\CPY\DRPA0367.CPv  $
      *
      *   Rev 2.1   May 28 1999 18:31:00   T13EX26
      *Prod-Übergabe 28.0598 hpa
      *
      *   Rev 2.0   May 26 1999 16:57:22   T13EX26
      *MFE-Umstellung
      *
      *   Rev 1.0   09 Jul 1997 16:04:22   P13PVCS
      *Initial revision.
      *
      *---------------------------------------------------------------*
      *
      *---------------------------------------------------------------*
       01  PI-UPPA0057.
           05 PI-UPPA0057-FUNKTION            PIC X(008).
              88 PI-UPPA0057-DRPA0368             VALUE 'DRPA0368'.
