      *---------------------------------------------------------------*
      *    Standard fuer alle Objekte unter PVCS VersionManager
      *            Datum      :  24.10.2018
      *            Kategorie  :  Copystrecke
      *---------------------------------------------------------------*
      *    Copyright (c) 2018 ATLAS Dienstleistungen f. V. GmbH
      *---------------------------------------------------------------*
      *    $Workfile:   DRPA1910.CPY  $
      *    $Revision:   2.1  $
      *
      *    $Log:   L:/mf/CPY/DRPA1910.CPv  $
      *
      *   Rev 2.1   Nov 12 2018 09:35:08   t13ae55
      *APA02711: Zählerüberläufe in PO23 und PMPA0040
      *
      *   Rev 2.0   Oct 24 2018 14:26:02   t13ae55
      *Archiverstellung
      *
      *---------------------------------------------------------------*
      ****************************************************************
      *    COPY-MEMBER: DRPA1910  FUNKTIONSAUFRUFE FÜR ZJPA0032      *
      *    -------------------------------------------------------   *
      *    ERSTELLT: M.NIX                                           *
      *    DATUM:    25.10.18                                        *
      ****************************************************************
      *    VERSION   01                                              *
      ****************************************************************
      * AENDERUNGEN:                                                 *
      * AUFTRAG ! DATUM  !VER ! AENDERUNG                 ! NAME     *
      * -------------------------------------------------------------*
      * APA02711!25.10.28! 01  ! NEUERSTELLUNG            ! M.NIX    *
      *                                                              *
      * ENDE-LOGBUCH                                                 *
      ****************************************************************
      *
 
       01  PI-ZJPA0032.
           05  PI-ZJPA0032-FUNKTION            PIC  X(008).
               88 PI-ZJPA0032-DRPA1911              VALUE 'DRPA1911'.
      *

