      *---------------------------------------------------------------*
      *    Standard f?r alle Objekte unter PVCS
      *            Datum   :  November 1995
      *            Kopf aus:  N:\PROFILE\KOPFCBL.DAT
      *---------------------------------------------------------------*
      *
      *---------------------------------------------------------------*
      *    Copyright 1995 ATLAS Dienstleistungs GmbH
      *---------------------------------------------------------------*
      *    $Workfile:   DRPA0352.CPY  $
      *    $Revision:   2.0  $
      *
      *    $Log:   L:\MF\CPY\DRPA0352.CPv  $
      *
      *   Rev 2.0   Jul 24 1999 11:35:10   T13EX25
      *APA00046, Neuerstellung
      *
      *   Rev 1.0   09 Jul 1997 16:02:02   P13PVCS
      *Initial revision.
      *
      *---------------------------------------------------------------*
